[window]
dimensions = { columns = 181, lines = 80 }
padding = { x = 8, y = 4 }

[cursor]
style = "Beam"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 12.0

normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }

offset = { x = 0, y = 1 }
